name: Docker

on:
  pull_request:

env:
  IMAGE_NAME: ombi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Identify version to build
        run: egrep "^ENV OMBI_VERSION=" Dockerfile | sed "s|^ENV ||" >> $GITHUB_ENV

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --cache-from ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest
